# Generated by Django 4.1.4 on 2022-12-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_records',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
