# Generated by Django 4.1.4 on 2022-12-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0002_alter_my_records_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_records',
            name='Status',
        ),
        migrations.AddField(
            model_name='my_records',
            name='Total_Deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='my_records',
            name='Total_confarmid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='my_records',
            name='Total_recovered',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='my_records',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
